export { default as Patient } from './Patient'
export { default as Appointment } from './Appointment'
export { default as Tooth } from './Tooth'
export { default as Formula } from './Formula'
export { default as Phone } from './Phone'
